name: CI

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    env:
      JOBS: 4
      FTK_API: GL_4_1
      FTK_SDL2: ON
      FTK_SDL3: OFF
      FTK_NFD: OFF
      FTK_PYTHON: ON
      FTK_TESTS: ON
      FTK_EXAMPLES: ON
      FTK_GCOV: ON
      BUILD_SHARED_LIBS: OFF

    steps:
    - uses: actions/checkout@v4
      with:
        path: feather-tk
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$PWD/install-Debug/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        sh feather-tk/etc/Linux/linux-setup-gha.sh

    - name: Build
      run: sh feather-tk/etc/Linux/linux-build-gha.sh Debug

    - name: Run tests
      run: |
        cd build-Debug
        xvfb-run ctest --verbose --rerun-failed --output-on-failure -C Debug
    
    - name: Code coverage
      if: env.FTK_GCOV == 'ON'
      run: |
        cd build-Debug
        sh ../feather-tk/etc/Linux/lcov.sh

  linux-sdl3-build:
    runs-on: ubuntu-latest

    env:
      JOBS: 4
      FTK_API: GL_4_1
      FTK_SDL2: OFF
      FTK_SDL3: ON
      FTK_NFD: OFF
      FTK_PYTHON: ON
      FTK_TESTS: ON
      FTK_EXAMPLES: ON
      FTK_GCOV: ON
      BUILD_SHARED_LIBS: OFF

    steps:
    - uses: actions/checkout@v4
      with:
        path: feather-tk
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$PWD/install-Debug/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        sh feather-tk/etc/Linux/linux-setup-gha.sh

    - name: Build
      run: sh feather-tk/etc/Linux/linux-build-gha.sh Debug

    - name: Run tests
      run: |
        cd build-Debug
        xvfb-run ctest --verbose --rerun-failed --output-on-failure -C Debug
    
    - name: Code coverage
      if: env.FTK_GCOV == 'ON'
      run: |
        cd build-Debug
        sh ../feather-tk/etc/Linux/lcov.sh

  linux-gles2-build:
    runs-on: ubuntu-latest

    env:
      JOBS: 4
      FTK_API: GLES_2
      FTK_SDL2: ON
      FTK_SDL3: OFF
      FTK_NFD: OFF
      FTK_PYTHON: ON
      FTK_TESTS: ON
      FTK_EXAMPLES: ON
      FTK_GCOV: OFF
      BUILD_SHARED_LIBS: OFF

    steps:
    - uses: actions/checkout@v4
      with:
        path: feather-tk
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$PWD/install-Debug/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        sh feather-tk/etc/Linux/linux-setup-gha.sh

    - name: Build
      run: sh feather-tk/etc/Linux/linux-build-gha.sh Debug

    - name: Run tests
      run: |
        cd build-Debug
        xvfb-run ctest --verbose --rerun-failed --output-on-failure -C Debug

  macos-15-intel-build:
    runs-on: macos-15-intel

    env:
      JOBS: 4
      FTK_API: GL_4_1
      FTK_SDL2: ON
      FTK_SDL3: OFF
      FTK_NFD: OFF
      FTK_PYTHON: ON
      FTK_TESTS: ON
      FTK_EXAMPLES: OFF
      FTK_GCOV: OFF
      BUILD_SHARED_LIBS: OFF
      CMAKE_OSX_DEPLOYMENT_TARGET: 10.15
      CMAKE_OSX_ARCHITECTURES: x86_64

    steps:
    - uses: actions/checkout@v4
      with:
        path: feather-tk
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # \bug DYLD_LIBRARY_PATH is not being set here?
    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        cmake --version
        python --version

    - name: Build
      run: |
        export DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH
        sh feather-tk/etc/macOS/macos-build-gha.sh Debug

    - name: Run tests
      run: |
        export DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH
        cd build-Debug
        ctest --verbose --rerun-failed --output-on-failure -C Debug

  macos-build:
    runs-on: macos-latest

    env:
      JOBS: 4
      FTK_API: GL_4_1
      FTK_SDL2: ON
      FTK_SDL3: OFF
      FTK_NFD: OFF
      FTK_PYTHON: ON
      FTK_TESTS: ON
      FTK_EXAMPLES: OFF
      FTK_GCOV: OFF
      BUILD_SHARED_LIBS: OFF
      CMAKE_OSX_DEPLOYMENT_TARGET: 14
      CMAKE_OSX_ARCHITECTURES: arm64

    steps:
    - uses: actions/checkout@v4
      with:
        path: feather-tk
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # \bug DYLD_LIBRARY_PATH is not being set here?
    - name: Setup environment
      run: |
        echo "$PWD/install-Debug/bin" >> $GITHUB_PATH
        echo "DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "PYTHONPATH=$PWD/install-Debug/lib:$PYTHONPATH" >> $GITHUB_ENV
        cmake --version
        python --version

    - name: Build
      run: |
        export DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH
        sh feather-tk/etc/macOS/macos-build-gha.sh Debug

    - name: Run tests
      run: |
        export DYLD_LIBRARY_PATH=$PWD/install-Debug/lib:$DYLD_LIBRARY_PATH
        cd build-Debug
        ctest --verbose --rerun-failed --output-on-failure -C Debug

  windows-build:
    runs-on: windows-latest

    env:
      JOBS: 4
      FTK_API: GL_4_1
      FTK_SDL2: ON
      FTK_SDL3: OFF
      FTK_NFD: OFF
      FTK_PYTHON: ON
      FTK_TESTS: ON
      FTK_EXAMPLES: OFF
      FTK_GCOV: OFF
      BUILD_SHARED_LIBS: OFF

    steps:
    - uses: actions/checkout@v4
      with:
        path: feather-tk
        submodules: recursive
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # \bug Any spaces before the ">>" will be considered part of the path.
    - name: Setup environment
      shell: cmd
      run: |
        echo %CD%\install-Debug\bin>> %GITHUB_PATH%
        echo %CD%\install-Debug\lib>> %GITHUB_PATH%
        echo PYTHONPATH=%CD%\install-Debug\lib >> %GITHUB_ENV%
        cmake --version

    - name: Build
      shell: cmd
      run: feather-tk\etc\Windows\windows-build-gha.bat Debug

    - name: Run tests
      shell: cmd
      run: |
        cd build-Debug
        ctest --verbose --rerun-failed --output-on-failure -C Debug

